### ISSUE TITLE
[BUG] the app crashes after downloading the first video of a playlist

### ISSUE THREAD

**Issue by not-programmer98** [deniscerri/ytdlnis#343] opened 2023-11-29 19:17 UTC
**To Reproduce**
The url I tried
https://youtube.com/playlist?list=PLUl4u3cNGP60IKRN_pFptIBxeiMc0MCJP&si=wFeBsSV9GwePUhUS

**(please complete the following information):**
 - Android Version: 12
 - App Version: 1.6.9

**Comment by zaednasr** [comment] 2023-11-29 19:35
Can you give me some more information? Can you use the app logfox to look at the crash log of the app?

**Comment by zaednasr** [comment] 2023-11-30 18:59
I think this is a duplicate of #344. It has been resolved

**Closed by zaednasr** 2023-11-30 18:59 UTC
Labels: bug
