### ISSUE TITLE
SponsorBlock related error

### ISSUE THREAD

**Issue by ForegoneFrog** [deniscerri/ytdlnis#379] opened 2024-01-15 15:47 UTC
Here's the log of my issue :- 

 --no-quiet --no-simulate --print "after_move:'%(filepath,_filename)s'" -N "3" --trim-filenames "211" --no-mtime --parse-metadata "%(channel,uploader,creator,artist|null)s:%(uploader)s" --parse-metadata "%(uploader)s:%(album_artist)s" --sponsorblock-mark "all" --embed-chapters -f "616+ba/616+ba/616/b" --embed-subs --sub-langs "en.*,.*-orig" --write-auto-subs -P "/storage/emulated/0/Download/Youtube Videos" -o "%(uploader,channel)s - %(title)s.%(ext)s" --replace-in-metadata "title" ".+" "CGI Animated Short: "Extinguished" - by Ashley Anderson & Jacob Mann + Ringling | TheCGBros" --replace-in-metadata "uploader" ".+" "TheCGBros" --replace-in-metadata "uploader" " - Topic$" " " "https://youtu.be/TvoAxorui0M"

WARNING: Unable to communicate with SponsorBlock API: HTTP Error 503: Service Temporarily Unavailable. Retrying (1/3)...
WARNING: Unable to communicate with SponsorBlock API: HTTP Error 500: Internal Server Error. Retrying (2/3)...
WARNING: Unable to communicate with SponsorBlock API: HTTP Error 504: Gateway Time-out. Retrying (3/3)...
ERROR: Preprocessing: Unable to communicate with SponsorBlock API: HTTP Error 504: Gateway Time-out
ERROR: Preprocessing: Unable to communicate with SponsorBlock API: HTTP Error 504: Gateway Time-out

It says unable to communicate with sposnorblock

**Comment by zaednasr** [comment] 2024-01-15 15:57
Duplicate of #377

**Closed by zaednasr** 2024-01-15 15:57 UTC
Labels: bug
