### ISSUE TITLE
[BUG] redgifs.com only works using terminal (NSFW)

### ISSUE THREAD

**Issue by Junkyard5031** [deniscerri/ytdlnis#297] opened 2023-10-07 09:29 UTC
Just to be clear this is an NSFW site.

**Describe the bug**
If you try to download anything from redgifs using the UI then you get an error. I think this happens because it tries to download a different URL than the one you entered. It tries to download some `thumb44.redgifs.com` url and gives an error about generic extractor.

**To Reproduce**
1. Go to `redgifs.com` **(NSFW)**
1. Click some username
1. Copy the url of a video on the user page
1. Paste it into ytdlnis.
1. Scroll down the menu with the download options and note that it's a different URL than the one you posted
1. Download it.

Then you get a an error "unable to download generic web page" and something else i can't parse from the error.

1. Open the terminal
1. Paste in the url after the command
1. Run command.

The video downloads because it didn't change the url. (or that's my theory)

**Expected behavior**
First of all it should download the video but it should also try to download the URL you entered and nothing else right? Is that a feature of trying to parsing and then editing URLs before downloading them? Sounds like a thing that could cause more bugs, a setting to disable could be nice.

**Screenshots / Video Recording**
Should be easy to reproduce yourself.

**(please complete the following information):**
 - Android Version: 13
 - App Version: v1.6.7
 - Other Device Information:

**Additional context**
Is there some way to get a log from the app? How are you supposed to share errors?

Other than that I would like to thank you for the fantastic app! :)

**Comment by deniscerri** [comment] 2023-10-07 09:33
yes you can get logs from the app, but not in this case. You can go to downloads and enable logs and it will log the downloads but i havent coded it to log the errors of fetching data before it. I should add this to the new release

Will look into this bug soon

**Comment by deniscerri** [comment] 2023-10-07 09:44
Perhaps try reinstalling the app from github as i had made small changes to it after the release u might have missed

**Comment by deniscerri** [comment] 2023-10-12 09:22
Try the beta

**Comment by Junkyard5031** [comment] 2023-10-12 16:04
Beta downloads videos now but when I try to use this app to open the file from with VLC then i get an error that says `the location fd://125 can't be played`, downloaded a random video from reddit as a test and that didn't happen when i tried to open that file.
Still the file is there and VLC can find when scanning for videos.
There is also no thumbnail for the video.

**Comment by deniscerri** [comment] 2023-10-12 16:06
Maybe redgifs didn't provide a thumbnail to ytdlp
Since you can play the file outside the app the problem is not that huge now. Will look into this.

Dm me the link on telegram if u can so i can see if i can replicate the issue

**Comment by Junkyard5031** [comment] 2023-10-12 18:46
I don't have telegram so I'll do this instead: `https://privatebin.net/?a50e516532878c11#5REzQxMe7mU5j8J1NefVLQmP5iC132N9PZ8RcKZNbi6`
This paste only works for one click.

**Comment by deniscerri** [comment] 2023-10-12 18:51
someone clicked it lol. Or u can dm me on discord if u have that. Its not a good idea to share nsfw in a public setting

**Comment by Junkyard5031** [comment] 2023-10-12 18:59
this one expires in 10 min but not one click, password is my username: `https://privatebin.net/?9f44a02c82b603d8#AvED2xXDKVeq13Cf6DvVBvxE8kQpktCq3hChwHbKCcMY`

**Comment by deniscerri** [comment] 2023-10-15 11:27
I downloaded multiple vids and they can open fine on other video players, so this could be a vlc issue. Since u can download the video fine now, im closing this

**Closed by deniscerri** 2023-10-15 11:27 UTC
Labels: bug
