### ISSUE TITLE
[Enhancement] Add Youtube Channel Playlist URL for result items

### ISSUE THREAD

**Issue by Turkialh14** [deniscerri/ytdlnis#615] opened 2024-11-12 20:44 UTC
### ⠀

- [X] Tried latest version

### ⠀

- [X] This issue is not duplicated with any other open or closed issues

### Describe the bug

When I download certain channels in full, not all videos are downloaded, only the first two videos, and also while the program is trying to download the channel, when I go to the history (it was deleted before testing), I see that there are six videos trying to download, although I have selected only three videos to download from, and the program's default download was used, in addition to a custom template, although I have modified it several times, but it still faces the same problem. And the videos that have not been downloaded as you see them in the small screen video, this is how they are scrolled quickly.

### Steps to reproduce

1- Open the application
2- Enter the channel link and wait for it to download
https://youtube.com/@pulsartech
3- Download all and choose either the default download or the custom template.
![Screenshot_٢٠٢٤١١١٢_٢٣٢٩٥١_Gallery](https://github.com/user-attachments/assets/2a19a4ea-7375-4bed-be41-895933345039)
![Screenshot_٢٠٢٤١١١٢_٢٣٣٠٠٤_Gallery](https://github.com/user-attachments/assets/b5bab19b-1d9b-4981-9743-d193a8492601)
![Screenshot_٢٠٢٤١١١٢_٢٣٣٠٢٢_Gallery](https://github.com/user-attachments/assets/4703df90-3c52-40c5-86e4-55049f414e1a)
![Screenshot_٢٠٢٤١١١٢_٢٣٤٢٥٧_Gallery](https://github.com/user-attachments/assets/9dbdd7bb-9cbd-4160-87cc-d646180849ad)

https://github.com/user-attachments/assets/5bc082df-39c3-4c4c-8f05-a30029294ffd

### Device information

Galaxy A54 5G
Android:14

### Additional context

Custom template:

-N "6" --retries "10" --fragment-retries "10" --buffer-size "6144" --no-resize-buffer --socket-timeout "120" --cookies "/data/user/0/com.deniscerri.ytdl/cache/cookies.txt" --trim-filenames "181" --no-mtime --extractor-args "youtube:player_client=default,mediaconnect,android,web" -S "+hasaud,res:1080,tbr" --force-keyframes-at-cuts --remux-video mkv -f "bv+ba/b" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/" -o "%(title)s %(id)s.%(ext)s" --parse-metadata "%(uploader,channel,creator,artist|null)s:^(?P<uploader>.*?)(?:(?= - Topic)|$)"

Directing one of the videos that was downloaded and it is among the first two:

Downloading:
Title: Step-by-Step Guide: Install Any Linux Distro on VirtualBox
URL: https://www.youtube.com/watch?v=j_3qNX99hzM
Type: command
Command: 
 -I "2:2" -N "6" --retries "10" --fragment-retries "10" --buffer-size "6144" --no-resize-buffer --socket-timeout "120" --cookies "/data/user/0/com.deniscerri.ytdl/cache/cookies.txt" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/5218" -N "6" --retries "10" --fragment-retries "10" --buffer-size "6144" --no-resize-buffer --socket-timeout "120" --cookies "/data/user/0/com.deniscerri.ytdl/cache/cookies.txt" --trim-filenames "181" --no-mtime --extractor-args "youtube:player_client=default,mediaconnect,android,web" -S "+hasaud,res:1080,tbr" --force-keyframes-at-cuts --remux-video mkv -f "bv+ba/b" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/" -o "%(title)s %(id)s.%(ext)s" --parse-metadata "%(uploader,channel,creator,artist|null)s:^(?P<uploader>.*?)(?:(?= - Topic)|$)" "https://youtube.com/@pulsartech" 

[youtube:tab] Extracting URL: https://youtube.com/@pulsartech
[youtube:tab] @pulsartech: Downloading webpage

Second output of one of the videos that has not been downloaded:

Downloading:
Title: 3 Simple Steps to Remove Graphics Card from PC
URL: https://www.youtube.com/watch?v=vVgnWBrzLTM
Type: command
Command: 
 -I "33:33" -N "6" --retries "10" --fragment-retries "10" --buffer-size "6144" --no-resize-buffer --socket-timeout "120" --cookies "/data/user/0/com.deniscerri.ytdl/cache/cookies.txt" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/5249" -N "6" --retries "10" --fragment-retries "10" --buffer-size "6144" --no-resize-buffer --socket-timeout "120" --cookies "/data/user/0/com.deniscerri.ytdl/cache/cookies.txt" --trim-filenames "181" --no-mtime --extractor-args "youtube:player_client=default,mediaconnect,android,web" -S "+hasaud,res:1080,tbr" --force-keyframes-at-cuts --remux-video mkv -f "bv+ba/b" -P "/storage/emulated/0/Android/data/com.deniscerri.ytdl/files/downloads/" -o "%(title)s %(id)s.%(ext)s" --parse-metadata "%(uploader,channel,creator,artist|null)s:^(?P<uploader>.*?)(?:(?= - Topic)|$)" "https://youtube.com/@pulsartech" 

[youtube:tab] Extracting URL: https://youtube.com/@pulsartech
[youtube:tab] @pulsartech: Downloading webpage
[youtube:tab] Downloading all uploads of the channel. To download only the videos in a specific tab, pass the tab's URL
[youtube:tab] @pulsartech/shorts: Downloading webpage
[youtube:tab] Downloading as multiple playlists, separated by tabs. To download as a single playlist instead, pass https://www.youtube.com/playlist?list=UUwlhDRn5h1huQnX7r_tu1FA
[download] Downloading playlist: PulsarTECH
[youtube:tab] Playlist PulsarTECH: Downloading 0 items of 2
[download] Finished downloading playlist: PulsarTECH

**Comment by deniscerri** [comment] 2024-11-16 14:29
https://github.com/yt-dlp/yt-dlp/issues/10827
This is already an issue we have opened to yt-dlp that is not yet implemented.
For the time being just turn on "Use Item URL instead of Playlist URL" in general settings

**Comment by Turkialh14** [comment] 2024-11-16 15:54
Ok, I get what you mean, how about I close it because it's a yt-dlp issue and it wouldn't be good to see so many issues unsolved?

**Comment by deniscerri** [comment] 2024-11-16 15:55
Lets leave it open, because if the issue is resolved, i need to make changes to the app to fix the issue in the app aswell

**Comment by Turkialh14** [comment] 2024-11-16 15:58
Ok

**Comment by deniscerri** [comment] 2024-11-17 17:45
For the time being, all youtube channel queries wont include the playlist url in them so they will be treated always like separate videos. Who cares about playlist metadata when its a channel i guess.
When the issue will be resolved, ill remove this ofc.

**Comment by Turkialh14** [comment] 2024-11-17 19:04
You are right

**Comment by deniscerri** [comment] 2024-12-06 18:13
Oh this was implemented btw, i forgor to close this

**Closed by deniscerri** 2024-12-06 18:13 UTC
Labels: enhancement, yt-dlp related
