### ISSUE TITLE
[BUG] Notification message conflict.

### ISSUE THREAD

**Issue by ghost** [deniscerri/ytdlnis#284] opened 2023-09-17 16:27 UTC
**Describe the bug**
The language I define in the application is Brazilian Portuguese. But the messages presented in the notifications are in European Portuguese.

**Expected behavior**
Brazilian Portuguese Language

**(please complete the following information):**
 - Android Version: 10
 - App Version: 1.6.7
 - Other Device Information: Samsung J6

**Comment by deniscerri** [comment] 2023-09-17 16:28
This is a bad translation. Go to weblate and fix it

**Comment by gigoloinc** [comment] 2023-09-17 16:52
The translations into Brazilian Portuguese are all correct on the weblate. the bug is in the application itself.

**Comment by deniscerri** [comment] 2023-09-17 16:56
hm. Does the rest of the app have brazilian portugese or normal portugese?

**Comment by gigoloinc** [comment] 2023-09-17 17:01
BE YOURSELF
PT-BR: https://github.com/deniscerri/ytdlnis/blob/2964f7da7593c1118d9f29daab32c727783b817b/app/src/main/res/values-pt-rBR/strings.xml#L35

PT-PT: https://github.com/deniscerri/ytdlnis/blob/2964f7da7593c1118d9f29daab32c727783b817b/app/src/main/res/values-pt/strings.xml#L40

**Comment by gigoloinc** [comment] 2023-09-17 17:04
The problem is only with the notification. The application is entirely in Brazilian Portuguese.

**Comment by gigoloinc** [comment] 2023-09-17 17:08
![Screenshot_20230917-140742](https://github.com/deniscerri/ytdlnis/assets/145172955/bb89da1e-cc4c-4d2d-811e-7711bb009e7c)

**Comment by deniscerri** [comment] 2023-09-17 17:17
Strange. What i have noticed is that langauges that have a normal name work ok but languages with - like pt-br or bn-in give you english instead

This could be a bad language code issue. Do you know what the correct code should be?

**Comment by gigoloinc** [comment] 2023-09-17 17:26
**PT** (Global Portuguese) for all Portuguese-speaking countries.
**PT-PT** (European Portuguese)
**PT-BR** (Brazilian Portuguese)

**Comment by deniscerri** [comment] 2023-09-17 17:31
yes thats how its written. 🤔🤔

**Comment by gigoloinc** [comment] 2023-09-17 17:31
Perhaps it would be better to change the code "pt" to "pt-pt". would probably solve the problem.

**Comment by deniscerri** [comment] 2023-09-17 17:32
but in my case, i dont even get portugese instead. I just get english. Does android not like those variant languages? not sure

**Comment by gigoloinc** [comment] 2023-09-17 17:36
So, perhaps Android is selecting the “pt” code as it does not indicate the exact location of the country.

**Comment by deniscerri** [comment] 2023-09-17 18:11
I updated the release. Try now

**Comment by gigoloinc** [comment] 2023-09-17 19:36
![iMarkup_20230917_162410](https://github.com/deniscerri/ytdlnis/assets/145172955/35e42a31-3a76-4115-9382-c1c035329d36)
![iMarkup_20230917_163200](https://github.com/deniscerri/ytdlnis/assets/145172955/dc5f5a7d-f308-4aa6-9626-2333a00c5ca9)
![iMarkup_20230917_162547](https://github.com/deniscerri/ytdlnis/assets/145172955/7b9c4b83-cdb9-47be-8509-0da724e9b30c)
![iMarkup_20230917_162626](https://github.com/deniscerri/ytdlnis/assets/145172955/53bd975c-7ed6-4b35-ae9c-bc085d967eb3)
![iMarkup_20230917_163609](https://github.com/deniscerri/ytdlnis/assets/145172955/61ec4952-bcfb-4320-80b4-07ef781974c5)

**Comment by gigoloinc** [comment] 2023-09-17 19:37
Did not work

**Comment by deniscerri** [comment] 2023-09-17 19:38
:/

**Comment by gigoloinc** [comment] 2023-09-17 19:41
I'll wait for the next release.

**Comment by deniscerri** [comment] 2023-09-17 19:43
come to telegram

**Comment by gigoloinc** [comment] 2023-10-12 17:23
Hello my friend!
Subject: Brazilian Portuguese.

YTDLnis version: 1.6.8.1-beta [arm]

When running the download it is OK!
![iMarkup_20231012_141045](https://github.com/deniscerri/ytdlnis/assets/145172955/8a4c0497-aae2-4883-a1fe-8cda9de1a0de)
After the download is complete, it returns to English.
![Screenshot_20231012-141231_Chrome](https://github.com/deniscerri/ytdlnis/assets/145172955/a30f38f7-e781-4e04-8c86-fab9b3278214)

**Comment by gigoloinc** [comment] 2023-10-12 17:34
Your app is wonderful. It's no surprise that today when I installed your app (beta version), Google showed me a warning saying that your app could pose a big risk to me.

**Comment by deniscerri** [comment] 2023-10-12 17:48
Google hates the yt-dlp library but it does that for any sideloaded app anyway. This language thing is annoying for sure. Still havent found the fix for it. Will keep on looking

**Comment by gigoloinc** [comment] 2023-10-12 17:57
Ok man, I'll be waiting for new improvements...

**Comment by deniscerri** [comment] 2023-10-15 12:24
I think i fixed it. But it will only show english in the notification if you kill the app. If you leave it in the background it should give the correct string. Hopefully it works when you try it in release

**Comment by gigoloinc** [comment] 2023-10-15 23:19
I'll wait for the next release. 🚀

**Comment by gigoloinc** [comment] 2023-10-15 23:21
> come to telegram

I don't use Telegram, just WhatsApp.

**Comment by gigoloinc** [comment] 2023-10-15 23:48
Problem solved.
![Screenshot_20231015-203735_ReVanced Extended](https://github.com/deniscerri/ytdlnis/assets/145172955/4023616f-282d-4991-acc7-43ff49b2a644)
![Screenshot_20231015-203811_ReVanced Extended](https://github.com/deniscerri/ytdlnis/assets/145172955/af1eb9a7-c319-4b20-a3f1-5c3f3eb25953)

**Comment by gigoloinc** [comment] 2023-10-15 23:52
### Problem solved. 
But to resolve this it was necessary to follow the following steps: 
1. Uninstall the application. 
2. Restart your device. 
3. Install the application. 
4. Open the app settings. 
5. Change the application language to “pt-br” instead of “portuguese”.

**Comment by gigoloinc** [comment] 2023-10-16 14:17
I found out that the problem is related to the location of the video. for example: when I download a video in Portuguese, notifications are shown in Portuguese, when I download a video in English, notifications are shown in English.

**Comment by deniscerri** [comment] 2023-10-16 14:18
No that's not related

**Comment by gigoloinc** [comment] 2023-10-30 19:17
I'm closing this issue due to lack of developer interest.

**Comment by deniscerri** [comment] 2023-10-30 19:47
@gigoloinc keep it open. I have experimented and i have noticed that if the activity is alive, then the language is correct but if the activity is dead then it assumes the current android language instead of the app language 

thats why its in english. Now why this only happens for language variants i have no idea. Maybe one day ill fix it

**Comment by zaednasr** [comment] 2023-11-18 13:21
I think i found a way to fix this. wait for a future release

**Comment by zaednasr** [comment] 2023-11-27 16:45
check out the latest release

**Closed by zaednasr** 2023-11-27 16:45 UTC
Labels: bug

**Comment by inavleb** [comment] 2023-11-27 21:14
*OK, it's working perfectly. Thank you very much!*
**YTDLnis version:** `1.6.9 [arm]`
